version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/prompt_db
      - REDIS_HOST=redis
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongodb_data:
  redis_data: 